import bikeImg from './../../../assets/img/rent/bikeMin.svg'
const dataBikes = [
    {
        id: 0,
        type:'economical',
        frameSize: 13,
        brand: 'Schwinn',
        src: bikeImg,
        name: 'Городской велосипед Schwinn Traveler 13”',
        price: 45,
        helmet: false,
        lantern: false,
        lock: false
    },
    {
        id: 1,
        type:'economical',
        frameSize: 20,
        brand: 'Foxx',
        src: bikeImg,
        name: 'Городской велосипед Foxx 20”',
        price: 45,
        helmet: false,
        lantern: false,
        lock: false
    },
    {
        id: 2,
        type:'economical',
        frameSize: 22,
        brand: 'Schwinn',
        src: bikeImg,
        name: 'Городской велосипед Schwinn Traveler 22”',
        price: 45,
        helmet: false,
        lantern: false,
        lock: false
    },
    {
        id: 3,
        type:'economical',
        frameSize: 19,
        brand: 'Schwinn',
        src: bikeImg,
        name: 'Городской велосипед Schwinn Traveler 19”',
        price: 45,
        helmet: false,
        lantern: false,
        lock: false
    },
    {
        id: 4,
        type:'carbon',
        frameSize: 22,
        brand: 'Foxx',
        src: bikeImg,
        name: 'Карбоновый велосипед Foxx Traveler 22”',
        price: 180,
        helmet: false,
        lantern: false,
        lock: false
    },
    {
        id: 5,
        type:'carbon',
        frameSize: 13,
        brand: 'Schwinn',
        src: bikeImg,
        name: 'Карбоновый велосипед Schwinn Traveler 13”',
        price: 180,
        helmet: false,
        lantern: false,
        lock: false
    },
    {
        id: 6,
        type:'carbon',
        frameSize: 18,
        brand: 'Foxx',
        src: bikeImg,
        name: 'Карбоновый велосипед Foxx Traveler 18”',
        price: 180,
        helmet: false,
        lantern: false,
        lock: false
    },
    {
        id: 7,
        type:'mountain',
        frameSize: 22,
        brand: 'Schwinn',
        src: bikeImg,
        name: 'Горный велосипед Schwinn Traveler 22”',
        price: 90,
        helmet: false,
        lantern: false,
        lock: false
    },
    {
        id: 8,
        type:'mountain',
        frameSize: 19,
        brand: 'Schwinn',
        src: bikeImg,
        name: 'Горный велосипед Schwinn Traveler 20”',
        price: 90,
        helmet: false,
        lantern: false,
        lock: false
    },
    {
        id: 9,
        type:'mountain',
        frameSize: 22,
        brand: 'Foxx',
        src: bikeImg,
        name: 'Горный велосипед Foxx Traveler 22”',
        price: 90,
        helmet: false,
        lantern: false,
        lock: false
    },
    {
        id: 10,
        type:'mountain',
        frameSize: 13,
        brand: 'Schwinn',
        src: bikeImg,
        name: 'Горный велосипед Schwinn Traveler 13”',
        price: 90,
        helmet: false,
        lantern: false,
        lock: false
    },
    {
        id: 11,
        type:'aluminum',
        frameSize: 18,
        brand: 'Foxx',
        src: bikeImg,
        name: 'Алюминиевый велосипед Foxx Traveler 18”',
        price: 90,
        helmet: false,
        lantern: false,
        lock: false
    },
    {
        id: 12,
        type:'aluminum',
        frameSize: 22,
        brand: 'Schwinn',
        src: bikeImg,
        name: 'Алюминиевый велосипед Schwinn Traveler 22”',
        price: 90,
        helmet: false,
        lantern: false,
        lock: false
    },
    {
        id: 13,
        type:'aluminum',
        frameSize: 19,
        brand: 'Schwinn',
        src: bikeImg,
        name: 'Алюминиевый велосипед Schwinn Traveler 19”',
        price: 90,
        helmet: false,
        lantern: false,
        lock: false
    },
    {
        id: 14,
        type:'aluminum',
        frameSize: 22,
        brand: 'Foxx',
        src: bikeImg,
        name: 'Алюминиевый велосипед Foxx Traveler 22”',
        price: 90,
        helmet: false,
        lantern: false,
        lock: false
    },
]

export default dataBikes